- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: setup mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASS }}


# To avoid MySQL Error 1130 Host not allowed to connect to this MySQL Server from shipping server
- name: setup mysql root password for the second time
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASS }}
  ignore_errors: true
    

- name: enable and start mysql server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true
